### ISSUE TITLE
Automatically show charts in jupyter

### ISSUE THREAD

**Issue by dansbits** [lumean/svg-graph2#13]
I think this is a great library for plotting. One of the better plotting libraries for ruby.

I think it would be a good addition if graphs would display automatically in Jupyter and iRuby. I believe this would be a simple addition of a `to_iruby` method to the `SVG::Graph::Graph` class. I'm happy to put up a PR for this but wanted to get feedback on the idea first. Any thoughts?

**Comment by dansbits** [comment]
Checking back in. Any objections to adding this?

**Comment by lumean** [comment]
Hey Dan, no not at all. I think it's a nice idea, please feel free to submit a PR. Br Manuel
