### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by noraj** [lumean/svg-graph2#17]
The documentation here gives an ERROR 500: http://www.germane-software.com/software/SVG/SVG::Graph/doc
Hopefully rubygems auto-generate this: https://www.rubydoc.info/gems/svg-graph/2.2.0

**Comment by lumean** [comment]
Hi Alexandre,
thanks for noticing, I will update the readme. The docu you linked is indeed auto-generated (rubydoc.info) and should be up to date. Also the documentation link on https://rubygems.org/gems/svg-graph should be correct.
Cheers Manuel
