### ISSUE TITLE
dataPointLabel styling issues

### ISSUE THREAD

**Issue by marnen** [lumean/svg-graph2#21]
It looks like Graph#make_datapoint_text writes each datapoint's text twice, once on top of the other, to provide a background and help the text stand out. Unfortunately, one text object uses the class .dataPointLabel, while the other uses .dataPointLabel *plus some inline styling* to make the background. This is a problem for those of us who use our own CSS to style the SVG graphs, because the inline styling (which, BTW, has the background hard-coded to white) means that it's difficult or impossible to customize the backgrounds to do the right thing.

What I propose, then, is the following (and I'll make a pull request for it hopefully in the next day or so): keep .dataPointLabel on the foreground element, but create a new class called something like .dataPointLabelBackground for the background element, and put the styling there instead of inline. This should keep the graph's current behavior with the default CSS, but make custom CSS easier to apply. Sound good?

**Comment by marnen** [comment]
(Also, not sure why the camelCase in the class name. It's idiomatic neither for CSS nor for Ruby. But that's a minor point.)

**Comment by lumean** [comment]
thanks for the input, PR is welcome.Also feel free to change the camelCase.
