### ISSUE TITLE
Knockouts don't align with labels

### ISSUE THREAD

**Issue by marnen** [lumean/svg-graph2#29]
This is from the bar_horizontal.svg file written by svg-graph2's own test suite (viewed in Chrome 80, Mac OS 10.14 [Mojave]). This isn't desired behavior, right?

![image](https://user-images.githubusercontent.com/34378/79826989-25f87280-836b-11ea-9053-492c3f91997a.png)

**Comment by lumean** [comment]
Nope, that's a bug. But I guess would be quite hard to write a spec to catch that for any parameter combination on each graph? (I dont have much experience with Rspec, used only unittest in the past).

**Comment by marnen** [comment]
I shouldn’t think it would be that hard. You’d probably want to find the relevant XML elements and check that their x-coordinates are equal.
