### ISSUE TITLE
2 Y Axis

### ISSUE THREAD

**Issue by pinkynrg** [lumean/svg-graph2#8]
is it possible to create charts with 2 y axis?

**Comment by lumean** [comment]
Hi, I'm afraid currently it's not possible. You may want to take a look at c3js.Am 23.03.2018 21:54 schrieb Francesco Meli <notifications@github.com>:is it possible to create charts with 2 y axis?

**Comment by lumean** [comment]
With `2.2.0.beta` you can use the C3js graphs to achieve this. Please have a look at the examples / test folder for code examples.
Use `gem install svg-graph --pre` to install the beta.
